######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 9 17:50:31 2014
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += HelloQT.cpp
